/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-11-05 06:31:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MemberVO;
import java.util.ArrayList;

public final class board_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/web04_spring/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Movie/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1630767106276L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");

	MemberVO vo = (MemberVO) session.getAttribute("vo");

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fonts/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<link rel='stylesheet'\r\n");
      out.write("	href='//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css' />\r\n");
      out.write("<script\r\n");
      out.write("	src='//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js'></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/httpRequest.js\"></script>\r\n");
      out.write("<!-- MATERIAL DESIGN ICONIC FONT -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//	window.onload = function(){\r\n");
      out.write("//		document.getElementById(\"mt1\").checked = \"checked\";\r\n");
      out.write("//	}\r\n");
      out.write("\r\n");
      out.write("	function getMovieName(event) {\r\n");
      out.write("\r\n");
      out.write("		const nameId = event.target.id; // nameId에 id값(mt1) 저장\r\n");
      out.write("		const query = 'label[for=\"' + nameId + '\"]'  // label for가 mt1인 라벨을 찾아라\r\n");
      out.write("		const text = document.querySelector(query).innerText;  // label for가 mt1인 라벨 안의 text값을 가져와라.\r\n");
      out.write("															   // mt1 = 킬러의 보디가드2\r\n");
      out.write("		document.getElementById('movienameresult').innerText = text;  // div id가 movienameresult인곳에 킬러의 보디가드2를 저장.\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function getMovieplace(event) {\r\n");
      out.write("\r\n");
      out.write("		const placeId = event.target.id;\r\n");
      out.write("		const query = 'label[for=\"' + placeId + '\"]'\r\n");
      out.write("		const text = document.querySelector(query).innerText;\r\n");
      out.write("\r\n");
      out.write("		document.getElementById('movieplaceresult').innerText = text;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function getMoviedate(event) {\r\n");
      out.write("\r\n");
      out.write("		const dateId = event.target.id;\r\n");
      out.write("		const query = 'label[for=\"' + dateId + '\"]'\r\n");
      out.write("		const text = document.querySelector(query).innerText;\r\n");
      out.write("\r\n");
      out.write("		document.getElementById('moviedateresult').innerText = text;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function getMovietime(event) {\r\n");
      out.write("\r\n");
      out.write("		const timeId = event.target.id;\r\n");
      out.write("		const query = 'label[for=\"' + timeId + '\"]'\r\n");
      out.write("		const text = document.querySelector(query).innerText;\r\n");
      out.write("\r\n");
      out.write("		document.getElementById('movietimeresult').innerText = text;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function giveTime(f) {\r\n");
      out.write("		\r\n");
      out.write("		var moviename = document.getElementById('movienameresult').innerText;\r\n");
      out.write("		var movietheater = document.getElementById('movieplaceresult').innerText;\r\n");
      out.write("		var moviedate = document.getElementById('moviedateresult').innerText;\r\n");
      out.write("		var c_moviename = document.getElementById('');\r\n");
      out.write("		\r\n");
      out.write("		if (moviename == \"\" || movietheater == \"\" || moviedate == \"\") {\r\n");
      out.write("			alert(\"모든 것을 선택하고 눌러주세요!\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		var url = 'givemovielist.do';\r\n");
      out.write("		var param = \"moviename=\" + moviename + \"&movietheater=\"\r\n");
      out.write("				+ encodeURIComponent(movietheater) + \"&moviedate=\"\r\n");
      out.write("				+ encodeURIComponent(moviedate);\r\n");
      out.write("\r\n");
      out.write("		sendRequest(url, param, resModify, \"POST\");\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function resModify() {\r\n");
      out.write("\r\n");
      out.write("		if (xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("\r\n");
      out.write("			var data = xhr.responseText;\r\n");
      out.write("			var json = eval(data);\r\n");
      out.write("\r\n");
      out.write("			if (json[0].res == 'yes') {\r\n");
      out.write("				alert(\"시간을 불러왔습니다. 영화부터 다시 선택해주세요.\");\r\n");
      out.write("\r\n");
      out.write("				location.href = \"list.do\";\r\n");
      out.write("\r\n");
      out.write("			} else {\r\n");
      out.write("				alert(\"수정실패\");\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 영화이름, 극장, 날짜, 시간을 가지고와 좌석화면으로 이동\r\n");
      out.write("	function send(f) {\r\n");
      out.write("		var moviename = document.getElementById('movienameresult').innerText;\r\n");
      out.write("		var movietheater = document.getElementById('movieplaceresult').innerText;\r\n");
      out.write("		var moviedate = document.getElementById('moviedateresult').innerText;\r\n");
      out.write("		var movietime = document.getElementById('movietimeresult').innerText;\r\n");
      out.write("\r\n");
      out.write("		f.moviename.value = moviename;\r\n");
      out.write("		f.movietheater.value = movietheater;\r\n");
      out.write("		f.moviedate.value = moviedate;\r\n");
      out.write("		f.movietimelist.value = movietime;\r\n");
      out.write("\r\n");
      out.write("		f.action = \"seat.do\";\r\n");
      out.write("		f.submit();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".b1{\r\n");
      out.write("	font-color:red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer{\r\n");
      out.write("	margin-top: 1300px;\r\n");
      out.write("	border-top: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	font-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #FDFCF0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* header */\r\n");
      out.write(".movies {\r\n");
      out.write("	table-layout: fixed;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	border-top: 20px solid red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".movies td {\r\n");
      out.write("	border-top: 5px solid yellow;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead th:nth-child(1) {\r\n");
      out.write("	width: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead th:nth-child(2) {\r\n");
      out.write("	width: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead th:nth-child(3) {\r\n");
      out.write("	width: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead th:nth-child(4) {\r\n");
      out.write("	width: 35%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* //header */\r\n");
      out.write("\r\n");
      out.write("/* nav */\r\n");
      out.write(".radio input[type=\"radio\"] {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 1px;\r\n");
      out.write("	height: 1px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: -1px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	clip: rect(0, 0, 0, 0);\r\n");
      out.write("	border: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio input[type=\"radio\"]+label {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding-left: 30px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	-webkit-user-select: none;\r\n");
      out.write("	-moz-user-select: none;\r\n");
      out.write("	-ms-user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio input[type=\"radio\"]+label:before {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	top: -4px;\r\n");
      out.write("	width: 21px;\r\n");
      out.write("	height: 21px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	background: #fafafa;\r\n");
      out.write("	border: 1px solid #cacece;\r\n");
      out.write("	border-radius: 100%;\r\n");
      out.write("	box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.05), inset 0px -15px 10px -12px\r\n");
      out.write("		rgba(0, 0, 0, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio input[type=\"radio\"]+label:active:before, .checks input[type=\"radio\"]:checked+label:active:before\r\n");
      out.write("	{\r\n");
      out.write("	box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05), inset 0px 1px 3px\r\n");
      out.write("		rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio input[type=\"radio\"]:checked+label:before {\r\n");
      out.write("	background: #E9ECEE;\r\n");
      out.write("	border-color: #adb8c0;\r\n");
      out.write("}\r\n");
      out.write("/* \r\n");
      out.write(".radio{\r\n");
      out.write("  padding-right: 2px;\r\n");
      out.write("    margin-top: 2px;\r\n");
      out.write("    height: 300px;\r\n");
      out.write("    flex-grow: 1;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    overflow: scroll;\r\n");
      out.write("    overflow-x: hidden;} */\r\n");
      out.write(".button {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	background-color: #4CAF50; /* Green */\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 16px 32px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin: 4px 2px;\r\n");
      out.write("	-webkit-transition-duration: 0.4s; /* Safari */\r\n");
      out.write("	transition-duration: 0.4s;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	color: black;\r\n");
      out.write("	border: 2px solid #4CAF50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover {\r\n");
      out.write("	background-color: #4CAF50;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".welcome {border =\"0\" margin-left:0px;\r\n");
      out.write("	margin-right: 0px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".welcome td {\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("	padding-top: 3px;\r\n");
      out.write("	padding-bottom: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".welcome button {\r\n");
      out.write("	background-color: #4CAF50; /* Green */\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 5px 8px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 4px;\r\n");
      out.write("	margin: 4px 2px;\r\n");
      out.write("	-webkit-transition-duration: 0.4s; /* Safari */\r\n");
      out.write("	transition-duration: 0.4s;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".moviesinside {\r\n");
      out.write("	border-top: 5px solid black;\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	margin-right: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".moviesinside2 {\r\n");
      out.write("	border-top: 5px solid black;\r\n");
      out.write("	margin-left: 80px;\r\n");
      out.write("	margin-right: 40px;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".moviesinside3 {\r\n");
      out.write("	border-top: 5px solid black;\r\n");
      out.write("	float: left;\r\n");
      out.write("	\r\n");
      out.write("	margin-left: 170px;\r\n");
      out.write("	margin-right: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".moviesinside4 {\r\n");
      out.write("	border-top: 5px solid black;	\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-left: 160px;\r\n");
      out.write("	margin-right: 60px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<form>\r\n");
      out.write("		<table class=\"welcome\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				");

					if (vo != null) {
				
      out.write("\r\n");
      out.write("				<td><input type=\"button\" value=\"마이페이지\" class=\"welcomebutton\"\r\n");
      out.write("					style=\"margin-top: 10px;\" onclick=\"location.href='moveMypage.do'\"></td>\r\n");
      out.write("\r\n");
      out.write("				<td><input type=\"button\" value=\"로그아웃\" class=\"welcomebutton\"\r\n");
      out.write("					style=\"margin-top: 10px;\" onclick=\"location.href='login_form.do'\"></td>\r\n");
      out.write("\r\n");
      out.write("				");

					} else {
				
      out.write("\r\n");
      out.write("				<td><input type=\"button\" value=\"마이페이지\" class=\"button\"\r\n");
      out.write("					style=\"margin-top: 10px;\" onclick=\"location.href='moveMypage.do'\"></td>\r\n");
      out.write("\r\n");
      out.write("				<td><input type=\"button\" value=\"로그인\" class=\"button\"\r\n");
      out.write("					style=\"margin-top: 10px;\" onclick=\"location.href='login_form.do'\"></td>\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<nav>\r\n");
      out.write("			<div class=\"logo-wrapper\">\r\n");
      out.write("				<a href=\"main.do\"> <img class=\"cgvLogo\"\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cgv.png\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"nav-content\">\r\n");
      out.write("				<div class=\"movieLogo-wrapper\">\r\n");
      out.write("					<img class=\"cgvMovie\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/h2_movie.png\">\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"nav-inner\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<button><a href=\"main.do\">영화</a></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<button style=\"border-bottom:3px solid gray;\"><a href=\"list.do\">예매</a></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<button>극장</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<button>이벤트&컬쳐</button>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div></div>\r\n");
      out.write("			<div></div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<table border=\"1\" align=\"center\" class=\"movies\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>영화</th>\r\n");
      out.write("				<th>영화관</th>\r\n");
      out.write("				<th>날짜</th>\r\n");
      out.write("				<th>시간</th>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<table class=\"moviesinside\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mt1' name=\"movietitle\" value='킬러의 보디가드2'\r\n");
      out.write("							onclick=\"getMovieName(event)\"><label for='mt1'>킬러의\r\n");
      out.write("							보디가드2</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mt2' name=\"movietitle\" value='발신제한'\r\n");
      out.write("							onclick=\"getMovieName(event)\"><label for='mt2'>발신제한</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mt3' name=\"movietitle\" value='콰이어트 플레이스2'\r\n");
      out.write("							onclick=\"getMovieName(event)\"><label for='mt3'>콰이어트\r\n");
      out.write("							플레이스2</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mt4' name=\"movietitle\" value='크루엘라'\r\n");
      out.write("							onclick=\"getMovieName(event)\"><label for='mt4'>크루엘라</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mt5' name=\"movietitle\" value='루카'\r\n");
      out.write("							onclick=\"getMovieName(event)\"><label for='mt5'>루카</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mt6' name=\"movietitle\"\r\n");
      out.write("							value='분노의 질주: 더 엘티메이텀' onclick=\"getMovieName(event)\"><label\r\n");
      out.write("							for='mt6'>분노의 질주: 더 엘티메이텀</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div id=\"movienameresult\" style=\"display: none\"></div> \r\n");
      out.write("					<input name=\"moviename\" type=\"hidden\">\r\n");
      out.write("				</td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<table class=\"moviesinside2\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp1' name=\"movieplace\" value='신촌'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp1'>신촌</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp2' name=\"movieplace\" value='강변'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp2'>강변</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp3' name=\"movieplace\" value='건대입구'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp3'>건대입구</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp4' name=\"movieplace\" value='구로'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp4'>구로</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp5' name=\"movieplace\" value='대학로'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp5'>대학로</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp6' name=\"movieplace\" value='동대문'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp6'>동대문</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp7' name=\"movieplace\" value='목동'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp7'>목동</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp8' name=\"movieplace\" value='명동'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp8'>명동</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp9' name=\"movieplace\" value='미아'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp9'>미아</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp10' name=\"movieplace\" value='불광'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp10'>불광</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp11' name=\"movieplace\" value='상봉'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp11'>상봉</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp12' name=\"movieplace\" value='송파'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp12'>송파</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp13' name=\"movieplace\" value='강변'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp13'>신촌</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp14' name=\"movieplace\" value='수유'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp14'>수유</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp15' name=\"movieplace\" value='압구정'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp15'>압구정</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp16' name=\"movieplace\" value='영등포'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp16'>영등포</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp17' name=\"movieplace\" value='왕십리'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp17'>왕십리</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='mp18' name=\"movieplace\" value='중계'\r\n");
      out.write("							onclick=\"getMovieplace(event)\"><label for='mp18'>중계</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><div id=\"movieplaceresult\" style=\"display: none\"></div> <input\r\n");
      out.write("					name=\"movietheater\" type=\"hidden\"></td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<table class=\"moviesinside3\" width=\"100\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md1' name=\"moviedate\" value='7월2일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md1'>7월2일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md2' name=\"moviedate\" value='7월 3일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md2'>7월 3일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md3' name=\"moviedate\" value='7월 4일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md3'>7월 4일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md4' name=\"moviedate\" value='7월 5일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md4'>7월 5일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md5' name=\"moviedate\" value='7월 6일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md5'>7월 6일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md6' name=\"moviedate\" value='7월 7일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md6'>7월 7일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md7' name=\"moviedate\" value='7월 8일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md7'>7월 8일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md8' name=\"moviedate\" value='7월 9일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md8'>7월 9일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio\">\r\n");
      out.write("						<input type=\"radio\" id='md9' name=\"moviedate\" value='7월 10일'\r\n");
      out.write("							onclick=\"getMoviedate(event)\"><label for='md9'>7월 10일</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><div id=\"moviedateresult\" style=\"display: none\"></div> <input\r\n");
      out.write("					name=\"moviedate\" type=\"hidden\"></td>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"button\" value=\"검색\" class=\"button\"\r\n");
      out.write("					onclick=\"giveTime(this.form);\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("        <div class=\"foot\">\r\n");
      out.write("        	<div class=\"logo\">\r\n");
      out.write("        		<img src=\"resources/img/logo.JPG\">\r\n");
      out.write("        	</div>\r\n");
      out.write("            <div class=\"sect-cinfo\">\r\n");
      out.write("                <p class=\"logo\">CJ CGV 로고</p>\r\n");
      out.write("                <h2>CJ CGV 회사소개 및 정책</h2>\r\n");
      out.write("                <div class=\"policy\">\r\n");
      out.write("                    <ul style=\"display: flex;\">\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/\" target=\"_blank\">회사소개</a></li> &nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/ir/financial/financial_list.aspx\" target=\"_blank\">IR</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/recruit/step/default.aspx\" target=\"_blank\">채용정보</a>&nbsp;&nbsp;\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/advertize/ad_Default.aspx\" target=\"_blank\">광고/프로모션문의</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/advertize/af_default.aspx\" target=\"_blank\">제휴문의</a>&nbsp;&nbsp;\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/advertize/bp_insert.aspx\" target=\"_blank\">출점문의</a>&nbsp;&nbsp;\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/service.aspx\">이용약관</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/organized.aspx\">편성기준</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/privacy.aspx\" class=\"empha-red\">개인정보처리방침</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/disclaimer.aspx\">법적고지</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/emreject.aspx\">이메일주소무단수집거부</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/company/coexist.aspx\">상생경영</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/guide/sitemap.aspx\">사이트맵</a></li>&nbsp;&nbsp;\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"share\">\r\n");
      out.write("                    <a href=\"https://www.facebook.com/CJCGV\" target=\"_blank\" class=\"facebook\" title=\"새창\">페이스북&nbsp;&nbsp;</a><a href=\"https://twitter.com/cj_cgv\" target=\"_blank\" class=\"twitter\" title=\"새창\">트위터&nbsp;&nbsp;</a><a href=\"https://www.instagram.com/cgv_korea/\" target=\"_blank\"\r\n");
      out.write("                        class=\"instagram\" title=\"새창\">인스타그램&nbsp;&nbsp;</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"address\">\r\n");
      out.write("                    <address>(04377)서울특별시 용산구 한강대로 23길 55, 아이파크몰 6층(한강로동)</address><br>\r\n");
      out.write("                    <p class=\"vl\">\r\n");
      out.write("                        <span>대표이사진 : 김재연 김유림 이인재 이상길  &nbsp;</span><br>\r\n");
      out.write("                        <span>사업자등록번호 : 104-81-45690</span><br>\r\n");
      out.write("                        <span>통신판매업신고번호 : 2017-서울용산-0662</span>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" onclick=\"goFtc()\" class=\"btn_goFtc\"><img src=\"http://img.cgv.co.kr/r2014/images/common/btn_reg.png\" alt=\"사업자정보확인\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"vl\">\r\n");
      out.write("                        <span>호스팅사업자 : CJ올리브네트웍스</span><br>\r\n");
      out.write("                        <span>개인정보보호 책임자 : 이인재</span> &nbsp;\r\n");
      out.write("                        <span>대표이메일 : cjcgvmaster@cj.net</span><br>\r\n");
      out.write("                        <span>CGV고객센터 : 1544-1122</span>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"copyright\">&copy; CJ CGV. All Rights Reserved</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"familysite\">\r\n");
      out.write("                    <label for=\"familysite\" class=\"hidden\">CJ그룹 계열사 바로가기</label>\r\n");
      out.write("                    <select id=\"familysite\">\r\n");
      out.write("                        <option value=\"\">계열사 바로가기</option>\r\n");
      out.write("                        <optgroup label=\"CJ그룹\">\r\n");
      out.write("                            <option value=\"http://www.cj.net/\">CJ주식회사</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"엔터테인먼트 & 미디어\">\r\n");
      out.write("                            <option value=\"http://www.cjenm.com/\">CJ ENM (E&M)</option>\r\n");
      out.write("                            <option value=\"http://www.cgv.co.kr/\">CJ CGV</option>\r\n");
      out.write("                            <option value=\"http://www.cjpowercast.com/\">CJ파워캐스트</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"식품 & 식품서비스\">\r\n");
      out.write("                            <option value=\"https://www.cj.co.kr\">CJ제일제당 (식품)</option>\r\n");
      out.write("                            <option value=\"http://www.cjfreshway.com/\">CJ프레시웨이</option>\r\n");
      out.write("                            <option value=\"http://www.cjfoodville.co.kr/\">CJ푸드빌</option>\r\n");
      out.write("                            <option value=\"http://www.md1.co.kr/\">CJ엠디원</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"생명공학\">\r\n");
      out.write("                            <option value=\"https://www.cj.co.kr/kr/about/business/bio\">CJ제일제당 (바이오)</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"신유통\">\r\n");
      out.write("                            <option value=\"http://display.cjmall.com\">CJ ENM (오쇼핑)</option>\r\n");
      out.write("                            <option value=\"http://www.cjlogistics.com\">CJ대한통운</option>\r\n");
      out.write("                            <option value=\"http://www.cjtelenix.com/\">CJ텔레닉스</option>\r\n");
      out.write("                            <option value=\"http://www.oliveyoung.co.kr/store/main/main.do\">CJ올리브영</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"인프라\">\r\n");
      out.write("                            <option value=\"http://www.cjenc.co.kr/\">CJ대한통운 (건설)</option>\r\n");
      out.write("                            <option value=\"http://www.cjolivenetworks.co.kr/itbusiness/\">CJ올리브네트웍스</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <button type=\"button\" title=\"새창\" onclick=\"goFamilySite()\">GO</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Float Ad -->\r\n");
      out.write("\r\n");
      out.write("        <!-- footer_area (e) -->\r\n");
      out.write("\r\n");
      out.write("        <!-- //Float Ad -->\r\n");
      out.write("      \r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/board/board_list.jsp(706,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.time}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div class=\"moviesinside4\">선택된 영화들이 없습니다.</div>\r\n");
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<table class=\"moviesinside4\">\r\n");
          out.write("					<!-- ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time.get(cnt.index)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" :  -->\r\n");
          out.write("					");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					<tr>\r\n");
          out.write("						<td><input type=\"button\" value=\"예매하기\" class=\"button\"\r\n");
          out.write("							onclick=\"send(this.form);\"></td>\r\n");
          out.write("					</tr>\r\n");
          out.write("					<tr>\r\n");
          out.write("						<td><div id=\"movietimeresult\" style=\"display: none\"></div> <input\r\n");
          out.write("							name=\"movietimelist\" type=\"hidden\"></td>\r\n");
          out.write("\r\n");
          out.write("					</tr>\r\n");
          out.write("				</table>\r\n");
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/board/board_list.jsp(713,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("value");
      // /WEB-INF/views/board/board_list.jsp(713,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/board_list.jsp(713,5) '${time}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${time}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/board_list.jsp(713,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("cnt");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			\r\n");
            out.write("						<tr>\r\n");
            out.write("							<td><input type=\"radio\" id='btn' name=\"movietime\"\r\n");
            out.write("								value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time.get(cnt.index)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" onclick=\"getMovietime(event)\"><label\r\n");
            out.write("								for='btn'>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time.get(cnt.index)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</label></td>\r\n");
            out.write("						</tr>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
