/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-11-05 07:06:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MemberVO;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/web04_spring/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Movie/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1630767106276L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.MemberVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	MemberVO vo = (MemberVO)session.getAttribute("vo");

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">	\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("   		<title>Document</title>\r\n");
      out.write("   		\r\n");
      out.write("    	<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    	\r\n");
      out.write("		<link rel=\"stylesheet\"\r\n");
      out.write("			  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\">\r\n");
      out.write("			  \r\n");
      out.write("		<link rel=\"stylesheet\"\r\n");
      out.write("			  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/reset.css\">\r\n");
      out.write("			  \r\n");
      out.write("		<link rel=\"stylesheet\"\r\n");
      out.write("			  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\">		\r\n");
      out.write("			  \r\n");
      out.write("	 	<link rel=\"stylesheet\" \r\n");
      out.write("	 		  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fonts/css/material-design-iconic-font.min.css\">\r\n");
      out.write("		 	\r\n");
      out.write("		<style>\r\n");
      out.write("			#main{\r\n");
      out.write("				height:1000px;\r\n");
      out.write("				border-bottom:1px solid gray;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			footer{\r\n");
      out.write("				margin-top: 500px;\r\n");
      out.write("				border-top: 1px solid gray;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	\r\n");
      out.write("		 <div class=\"header-nav-wrapper\">\r\n");
      out.write("         <header class=\"header\">\r\n");
      out.write("            <div class=\"header-inner\">\r\n");
      out.write("                <div><button><i class=\"zmdi zmdi-apps\"></i><span>&nbsp;CGV APP</span></button></div>\r\n");
      out.write("                <div><button><i class=\"zmdi zmdi-facebook-box\"></i><span>&nbsp;Like</span></button></div>\r\n");
      out.write("                <div><button><i class=\"zmdi zmdi-instagram\"></i><span>&nbsp;follow</span></button></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			 <div class=\"header-inner\">\r\n");
      out.write("				  ");
 if(vo != null){
                	
      out.write("\r\n");
      out.write("                	<div><button>");
      out.print(vo.getName());
      out.write("님 환영합니다</button></div>\r\n");
      out.write("                	<div><a href=\"mypage.do\"><button style=\"border-bottom:2px solid black;\">마이페이지</button></a></div>\r\n");
      out.write("                	<div><a href=\"logout.do\"><button>로그아웃</button></a></div>\r\n");
      out.write("                	");

                } else {
                	
      out.write("\r\n");
      out.write("                	<div><a href=\"login_form.do\"><button>로그인</button></a></div>\r\n");
      out.write("                	<div><a href=\"newmember.do\"><button>회원가입</button></a></div>\r\n");
      out.write("                	");

                }
                
      out.write(" \r\n");
      out.write("			</div>\r\n");
      out.write("	\r\n");
      out.write("		</header>\r\n");
      out.write("		 <nav class=\"nav-wrapper\">\r\n");
      out.write("            <div class=\"logo-wrapper\"><a href=\"main.do\">\r\n");
      out.write("            	<img class=\"cgvLogo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cgv.png\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav-content\">\r\n");
      out.write("                <div class=\"movieLogo-wrapper\">\r\n");
      out.write("                	<img class=\"cgvMovie\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/h2_movie.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-inner\">\r\n");
      out.write("                    <div><button style=\"border-bottom:4px solid black;\"><a href=\"main.do\">영화</a></button></div>\r\n");
      out.write("                    <div><button><a href=\"list.do\">예매</a></button></div>\r\n");
      out.write("                    <div><button>극장</button></div>\r\n");
      out.write("                    <div><button>이벤트&컬쳐</button></div>\r\n");
      out.write("                    <div class=\"search-wrapper\"><input><button class=\"searchButton\">검색</button></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div>\r\n");
      out.write("	        <div class=\"content-header-container\">\r\n");
      out.write("	            <div class=\"content-header-wrapper\">\r\n");
      out.write("	                <div class=\"content-header-title\">무비 차트</div>\r\n");
      out.write("	                <div class=\"content-header-menu\">\r\n");
      out.write("	                    <div class=\"chart\"><button class=\"selectedMenu\">무비차트</button></div>\r\n");
      out.write("	                    <div class=\"movie-notice\"><button>상영예정작</button></div>\r\n");
      out.write("	                    <div class=\"movie-house\"><button>CGV아트하우스</button></div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"movie-infomation-wrapper\">\r\n");
      out.write("	            </div>\r\n");
      out.write("	      	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("      	<div style=\" text-align:center; background-color:gray; color:white\" > 예약한 영화 목록 </div><br><br><br>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      	 ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("     	       \r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("	\r\n");
      out.write("		<footer>\r\n");
      out.write("        <div class=\"foot\">\r\n");
      out.write("        	<div class=\"logo\">\r\n");
      out.write("        		<img src=\"resources/img/logo.JPG\">\r\n");
      out.write("        	</div>\r\n");
      out.write("            <div class=\"sect-cinfo\">\r\n");
      out.write("                <p class=\"logo\">CJ CGV 로고</p>\r\n");
      out.write("                <h2>CJ CGV 회사소개 및 정책</h2>\r\n");
      out.write("                <div class=\"policy\">\r\n");
      out.write("                    <ul style=\"display: flex;\">\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/\" target=\"_blank\">회사소개</a></li> &nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/ir/financial/financial_list.aspx\" target=\"_blank\">IR</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/recruit/step/default.aspx\" target=\"_blank\">채용정보</a>&nbsp;&nbsp;\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/advertize/ad_Default.aspx\" target=\"_blank\">광고/프로모션문의</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/advertize/af_default.aspx\" target=\"_blank\">제휴문의</a>&nbsp;&nbsp;\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"http://corp.cgv.co.kr/company/advertize/bp_insert.aspx\" target=\"_blank\">출점문의</a>&nbsp;&nbsp;\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/service.aspx\">이용약관</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/organized.aspx\">편성기준</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/privacy.aspx\" class=\"empha-red\">개인정보처리방침</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/disclaimer.aspx\">법적고지</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/rules/emreject.aspx\">이메일주소무단수집거부</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/company/coexist.aspx\">상생경영</a></li>&nbsp;&nbsp;\r\n");
      out.write("                        <li><a href=\"http://www.cgv.co.kr/guide/sitemap.aspx\">사이트맵</a></li>&nbsp;&nbsp;\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"share\">\r\n");
      out.write("                    <a href=\"https://www.facebook.com/CJCGV\" target=\"_blank\" class=\"facebook\" title=\"새창\">페이스북&nbsp;&nbsp;</a><a href=\"https://twitter.com/cj_cgv\" target=\"_blank\" class=\"twitter\" title=\"새창\">트위터&nbsp;&nbsp;</a><a href=\"https://www.instagram.com/cgv_korea/\" target=\"_blank\"\r\n");
      out.write("                        class=\"instagram\" title=\"새창\">인스타그램&nbsp;&nbsp;</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"address\">\r\n");
      out.write("                    <address>(04377)서울특별시 용산구 한강대로 23길 55, 아이파크몰 6층(한강로동)</address><br>\r\n");
      out.write("                    <p class=\"vl\">\r\n");
      out.write("                        <span>대표이사진 : 김재연 김유림 이인재 이상길  &nbsp;</span><br>\r\n");
      out.write("                        <span>사업자등록번호 : 104-81-45690</span><br>\r\n");
      out.write("                        <span>통신판매업신고번호 : 2017-서울용산-0662</span>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" onclick=\"goFtc()\" class=\"btn_goFtc\"><img src=\"http://img.cgv.co.kr/r2014/images/common/btn_reg.png\" alt=\"사업자정보확인\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"vl\">\r\n");
      out.write("                        <span>호스팅사업자 : CJ올리브네트웍스</span><br>\r\n");
      out.write("                        <span>개인정보보호 책임자 : 이인재</span> &nbsp;\r\n");
      out.write("                        <span>대표이메일 : cjcgvmaster@cj.net</span><br>\r\n");
      out.write("                        <span>CGV고객센터 : 1544-1122</span>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"copyright\">&copy; CJ CGV. All Rights Reserved</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"familysite\">\r\n");
      out.write("                    <label for=\"familysite\" class=\"hidden\">CJ그룹 계열사 바로가기</label>\r\n");
      out.write("                    <select id=\"familysite\">\r\n");
      out.write("                        <option value=\"\">계열사 바로가기</option>\r\n");
      out.write("                        <optgroup label=\"CJ그룹\">\r\n");
      out.write("                            <option value=\"http://www.cj.net/\">CJ주식회사</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"엔터테인먼트 & 미디어\">\r\n");
      out.write("                            <option value=\"http://www.cjenm.com/\">CJ ENM (E&M)</option>\r\n");
      out.write("                            <option value=\"http://www.cgv.co.kr/\">CJ CGV</option>\r\n");
      out.write("                            <option value=\"http://www.cjpowercast.com/\">CJ파워캐스트</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"식품 & 식품서비스\">\r\n");
      out.write("                            <option value=\"https://www.cj.co.kr\">CJ제일제당 (식품)</option>\r\n");
      out.write("                            <option value=\"http://www.cjfreshway.com/\">CJ프레시웨이</option>\r\n");
      out.write("                            <option value=\"http://www.cjfoodville.co.kr/\">CJ푸드빌</option>\r\n");
      out.write("                            <option value=\"http://www.md1.co.kr/\">CJ엠디원</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"생명공학\">\r\n");
      out.write("                            <option value=\"https://www.cj.co.kr/kr/about/business/bio\">CJ제일제당 (바이오)</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"신유통\">\r\n");
      out.write("                            <option value=\"http://display.cjmall.com\">CJ ENM (오쇼핑)</option>\r\n");
      out.write("                            <option value=\"http://www.cjlogistics.com\">CJ대한통운</option>\r\n");
      out.write("                            <option value=\"http://www.cjtelenix.com/\">CJ텔레닉스</option>\r\n");
      out.write("                            <option value=\"http://www.oliveyoung.co.kr/store/main/main.do\">CJ올리브영</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"인프라\">\r\n");
      out.write("                            <option value=\"http://www.cjenc.co.kr/\">CJ대한통운 (건설)</option>\r\n");
      out.write("                            <option value=\"http://www.cjolivenetworks.co.kr/itbusiness/\">CJ올리브네트웍스</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <button type=\"button\" title=\"새창\" onclick=\"goFamilySite()\">GO</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Float Ad -->\r\n");
      out.write("\r\n");
      out.write("        <!-- footer_area (e) -->\r\n");
      out.write("\r\n");
      out.write("        <!-- //Float Ad -->\r\n");
      out.write("      \r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/main/mypage.jsp(109,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("value");
      // /WEB-INF/views/main/mypage.jsp(109,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/mypage.jsp(109,8) '${sessionScope.reservationlist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.reservationlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/main/mypage.jsp(109,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("cnt");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			<div class=\"movie-informaion\" style=\"border: 1px solid gray;\">\r\n");
            out.write("				<div class=\"movie-rank\">No.");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.index+1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("				<br>\r\n");
            out.write("				<div>\r\n");
            out.write("					<div class=\"moviedate\">날짜 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationlist.get(cnt.index).getReserveDate()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("					<div class=\"movietheater\">영화관 장소 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationlist.get(cnt.index).getSelectedTheater()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("					<div class=\"movietitle\">영화이름 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationlist.get(cnt.index).getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("					<div class=\"movietime\">영화시간 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationlist.get(cnt.index).getRunningTime()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("					<div class=\"movietime\">영화좌석 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationlist.get(cnt.index).getSelectedSeat()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("					\r\n");
            out.write("					<br>\r\n");
            out.write("	\r\n");
            out.write("				</div>\r\n");
            out.write("			</div>\r\n");
            out.write("\r\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
